stages:
    - release

before_script:
  - npm install

git-release:
  image: node:21.0.0
  stage: release
  script:
    - npx semantic-release

dockerhub-release:
  image: docker:cli
  stage: release
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_USER/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $DOCKER_USER/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $DOCKER_USER/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_USER/$DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_USER/$DOCKER_IMAGE_NAME:latest
