# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
    - release

before_script:
  - npm install

release:
  image: node:21.0.0
  stage: release
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - npx semantic-release
