version: "3.7"

services:
  go-todo-api:
    container_name: go-todo-api
    build: .
    restart: always
    environment:
      PRODUCTION: 1
      DATABASE_URL: mongodb://mongodb:27017
      DATABASE_NAME: default
    ports:
      - "8080:8080"
    networks:
      - go-todo-api
    depends_on:
      - mongodb
  mongodb:
    container_name: go-todo-api_mongodb
    image: mongo:7.0@sha256:192e2724093257a7db12db6cbafd92e3e5d51937f13846d49ea555cea85787ce
    ports:
      - "27017:27017"
    networks:
      - go-todo-api
    volumes:
      - mongodb:/data/db
    pull_policy: if_not_present
volumes:
  mongodb:
    name: go-todo-api_mongodb
networks:
  go-todo-api:
    driver: bridge
