version: "3.7"

services:
  go-todo-api:
    container_name: go-todo-api
    build: .
    restart: always
    environment:
      PRODUCTION: 1
      DATABASE_URL: mongodb://mongodb:27017
      DATABASE_NAME: default
    ports:
      - "8080:8080"
    networks:
      - go-todo-api
    depends_on:
      - mongodb
  mongodb:
    container_name: go-todo-api_mongodb
    image: mongo:7.0@sha256:3f765972fa2d1d0a748762ba43930f06f0c3ea58986582dd4663fe5ad7b63f0e
    ports:
      - "27017:27017"
    networks:
      - go-todo-api
    volumes:
      - mongodb:/data/db
    pull_policy: if_not_present
volumes:
  mongodb:
    name: go-todo-api_mongodb
networks:
  go-todo-api:
    driver: bridge
